# CMake generated Testfile for 
# Source directory: C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf
# Build directory: C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_div "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Debug/test-perf_matrix_div.exe")
  set_tests_properties(test-perf_matrix_div PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;1;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_div "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Release/test-perf_matrix_div.exe")
  set_tests_properties(test-perf_matrix_div PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;1;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_div "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/MinSizeRel/test-perf_matrix_div.exe")
  set_tests_properties(test-perf_matrix_div PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;1;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_div "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/RelWithDebInfo/test-perf_matrix_div.exe")
  set_tests_properties(test-perf_matrix_div PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;1;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_div NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_inverse "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Debug/test-perf_matrix_inverse.exe")
  set_tests_properties(test-perf_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;2;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_inverse "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Release/test-perf_matrix_inverse.exe")
  set_tests_properties(test-perf_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;2;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_inverse "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/MinSizeRel/test-perf_matrix_inverse.exe")
  set_tests_properties(test-perf_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;2;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_inverse "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/RelWithDebInfo/test-perf_matrix_inverse.exe")
  set_tests_properties(test-perf_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;2;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_inverse NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_mul "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Debug/test-perf_matrix_mul.exe")
  set_tests_properties(test-perf_matrix_mul PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;3;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_mul "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Release/test-perf_matrix_mul.exe")
  set_tests_properties(test-perf_matrix_mul PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;3;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_mul "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/MinSizeRel/test-perf_matrix_mul.exe")
  set_tests_properties(test-perf_matrix_mul PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;3;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_mul "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/RelWithDebInfo/test-perf_matrix_mul.exe")
  set_tests_properties(test-perf_matrix_mul PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;3;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_mul NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_mul_vector "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Debug/test-perf_matrix_mul_vector.exe")
  set_tests_properties(test-perf_matrix_mul_vector PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;4;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_mul_vector "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Release/test-perf_matrix_mul_vector.exe")
  set_tests_properties(test-perf_matrix_mul_vector PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;4;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_mul_vector "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/MinSizeRel/test-perf_matrix_mul_vector.exe")
  set_tests_properties(test-perf_matrix_mul_vector PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;4;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_mul_vector "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/RelWithDebInfo/test-perf_matrix_mul_vector.exe")
  set_tests_properties(test-perf_matrix_mul_vector PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;4;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_mul_vector NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_transpose "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Debug/test-perf_matrix_transpose.exe")
  set_tests_properties(test-perf_matrix_transpose PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;5;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_transpose "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Release/test-perf_matrix_transpose.exe")
  set_tests_properties(test-perf_matrix_transpose PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;5;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_transpose "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/MinSizeRel/test-perf_matrix_transpose.exe")
  set_tests_properties(test-perf_matrix_transpose PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;5;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_transpose "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/RelWithDebInfo/test-perf_matrix_transpose.exe")
  set_tests_properties(test-perf_matrix_transpose PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;5;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_transpose NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_vector_mul_matrix "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Debug/test-perf_vector_mul_matrix.exe")
  set_tests_properties(test-perf_vector_mul_matrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;6;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_vector_mul_matrix "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/Release/test-perf_vector_mul_matrix.exe")
  set_tests_properties(test-perf_vector_mul_matrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;6;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_vector_mul_matrix "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/MinSizeRel/test-perf_vector_mul_matrix.exe")
  set_tests_properties(test-perf_vector_mul_matrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;6;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_vector_mul_matrix "C:/Users/gcoh0/source/repos/LearnOpenGL/Dependencies/glm_x86/test/perf/RelWithDebInfo/test-perf_vector_mul_matrix.exe")
  set_tests_properties(test-perf_vector_mul_matrix PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/CMakeLists.txt;231;add_test;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;6;glmCreateTestGTC;C:/Users/gcoh0/source/repos/OpenGLTutorial/Dependencies/glm-master/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_vector_mul_matrix NOT_AVAILABLE)
endif()
